#!/usr/bin/env bash

cd "$(dirname "$0")"

git pull
git add .
git commit -m "rebuild $(date +%F_%T)"
git push

sudo nixos-rebuild boot -p "timonos-$(date +%F_%H-%M-%S)-$(git rev-parse --verify HEAD)" --show-trace $@ --flake .
