#!/usr/bin/env bash

cd "$(dirname "$0")"

git pull
git add .
git commit -m "rebuild $(date +%F_%T)"
git push

sudo nixos-rebuild boot -p "TimonOS $(git rev-parse --short HEAD) $(date +%F_%T)" --show-trace $@ --flake .
