#!/usr/bin/env bash

cd "$(dirname "$0")"

git pull
git add .
git commit -m "rebuild $(date +%F_%T)"
git push

sudo nixos-rebuild boot -p "timonos-$(git rev-parse --verify HEAD)-$(date +%F_%H_%M)" --show-trace $@ --flake .
