#!/usr/bin/env bash

mkdir tmp
cp appimage tmp/appimage
cd tmp
chmod +x appimage
./appimage --appimage-extract
mkdir unpacked
cp -r squashfs-root/* ./unpacked

mkdir patch
cd patch
mkdir app
mkdir webapp

asar extract /app/tmp/unpacked/resources/app.asar /app/tmp/patch/app
asar extract /app/tmp/unpacked/resources/webapp.asar /app/tmp/patch/webapp

echo ""
echo "Patching app..."

patch < /app/patches.yaml

echo ""
echo "Patching Done!!!"
echo ""

cd ../..
mkdir patched
cp -r tmp/unpacked/** patched/

asar pack /app/tmp/patch/app patched/resources/app.asar
asar pack /app/tmp/patch/webapp patched/resources/webapp.asar

wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
chmod a+x appimagetool-x86_64.AppImage
./appimagetool-x86_64.AppImage --appimage-extract-and-run patched/ patched.AppImage

cp patched.AppImage /app/appimage

# sleep infinity # to keep the container running
