#!/usr/bin/env bash

docker build -t beeper-patch .

cp -n .AppImage .AppImage.bak

cp .AppImage.bak .AppImage

docker run -it --name beeper-patch --rm -v $(pwd)/.AppImage:/app/appimage beeper-patch

cp .AppImage patched.AppImage

sudo chmod +x patched.AppImage
