#!/usr/bin/env sh
cd /tmp
sudo rm -f -r WhiteSur-gtk-theme
git clone git@github.com:vinceliuice/WhiteSur-gtk-theme.git
cd WhiteSur-gtk-theme
chmod +x ./install.sh
./install.sh -m -t all -l --normal --round
sudo ./tweaks.sh -g -b blank -c Dark -o solid
sudo ./tweaks.sh -f alt

cd /tmp
sudo rm -f -r WhiteSur-icon-theme
git clone git@github.com:vinceliuice/WhiteSur-icon-theme.git
cd WhiteSur-icon-theme
chmod +x ./install.sh
./install.sh -a

cd /tmp
sudo rm -f -r Colloid-icon-theme
git clone git@github.com:vinceliuice/Colloid-icon-theme.git
cd Colloid-icon-theme
chmod +x ./install.sh
./install.sh -t all
